NUMPY

In [1]:
import numpy as np

In [2]:
tuple=(1,2,3,)
list =[1,2,3]

In [3]:
arr_tuple = np.array(tuple)
arr_list = np.array(list)

In [4]:
print(arr_tuple)
print(arr_list)

[1 2 3]
[1 2 3]


In [6]:
list=[[1,2,3],[2,3,4],[4,6,8]]
arr_list = np.array(list)
print(arr_list)
print(arr_list.ndim)
print(arr_list.shape)
print(arr_list.size)
print(type(arr_list))
print(arr_list[0,0])
print(arr_list[:,1:3])


[[1 2 3]
 [2 3 4]
 [4 6 8]]
2
(3, 3)
9
<class 'numpy.ndarray'>
1
[[2 3]
 [3 4]
 [6 8]]


In [8]:
arr_zeroes = np.zeros((3,3))
print(arr_zeroes)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
arr_ones= np.ones((3,3))
print(arr_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
arr_random = np.random.random((3,3))
print(arr_random)

[[0.78663888 0.50293503 0.3550838 ]
 [0.33639297 0.01729082 0.47494543]
 [0.74251914 0.65208811 0.54238418]]


In [12]:
arr_random = np.random.randn(3,3)
print(arr_random)

[[ 0.06488348 -0.68832246 -2.14392051]
 [ 0.61212421 -1.16574132 -0.48794307]
 [-0.11300069  0.61520837  0.66546427]]


In [18]:
arr_random = np.random.randint(low=0,high=3,size=arr_list.shape)
print(arr_random)

[[0 2 0]
 [1 1 1]
 [1 0 2]]


In [20]:
arr_range=np.arange(0,20,2)
print(arr_range)

[ 0  2  4  6  8 10 12 14 16 18]


In [21]:
arr_space = np.linspace(0,20,11)
print(arr_space)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [22]:
arr_range_reshaped = arr_range.reshape(2,5)
print(arr_range_reshaped)

[[ 0  2  4  6  8]
 [10 12 14 16 18]]


In [23]:
arr_range_flatten = arr_range_reshaped.flatten()
print(arr_range_flatten)

[ 0  2  4  6  8 10 12 14 16 18]


In [29]:
arr=np.array([[1,2,3],[4,4,5],[5,6,8]])
print(arr)
print(arr + 1)
print(arr - 1)
print(arr * 2)
print(arr / 2)
print(arr ** 2)
print(arr.T)
print(arr + arr)
print(np.dot(arr , arr))


[[1 2 3]
 [4 4 5]
 [5 6 8]]
[[2 3 4]
 [5 5 6]
 [6 7 9]]
[[0 1 2]
 [3 3 4]
 [4 5 7]]
[[ 2  4  6]
 [ 8  8 10]
 [10 12 16]]
[[0.5 1.  1.5]
 [2.  2.  2.5]
 [2.5 3.  4. ]]
[[ 1  4  9]
 [16 16 25]
 [25 36 64]]
[[1 4 5]
 [2 4 6]
 [3 5 8]]
[[ 2  4  6]
 [ 8  8 10]
 [10 12 16]]
[[ 24  28  37]
 [ 45  54  72]
 [ 69  82 109]]


In [30]:
print(arr.max())
print(arr.min())
print(arr.sum())

8
1
38


In [31]:
print(arr.max(axis=0))
print(arr.max(axis=1))

[5 6 8]
[3 5 8]


In [32]:
print(np.sin(np.pi))
print(np.cos(np.pi))
print(np.exp(2))
print(np.log(np.exp(2)))
print(np.sqrt(4))

1.2246467991473532e-16
-1.0
7.38905609893065
2.0
2.0


In [35]:
arr = np.array([[1,5,9],[4,5,7],[7,6,7]])
print(np.sort(arr,axis=None))
print(np.sort(arr,axis=0))#col element sorting
print(np.sort(arr,axis=1))#row element sorting
print(arr>2)

[1 4 5 5 6 7 7 7 9]
[[1 5 7]
 [4 5 7]
 [7 6 9]]
[[1 5 9]
 [4 5 7]
 [6 7 7]]
[[False  True  True]
 [ True  True  True]
 [ True  True  True]]


In [37]:
print(arr[arr>2])

[5 9 4 5 7 7 6 7]


In [38]:
print(np.where(arr>2,arr,0))

[[0 5 9]
 [4 5 7]
 [7 6 7]]
